# GenerateCsoHeader.cmake
#
# Reads a compiled shader .cso (binary) and emits a C header containing the
# bytecode as a byte array, plus its size:
#
#   unsigned char g_raytracing_cso[] = { 0x.., ... };
#   unsigned g_raytracing_cso_size = <N>;
#
# Invoked as: cmake -DINPUT=<cso> -DOUTPUT=<header> -P GenerateCsoHeader.cmake
# If INPUT is omitted or missing, a stub header (size 0) is emitted instead.

set(_header_content "")

if(DEFINED INPUT AND EXISTS "${INPUT}")
    file(READ "${INPUT}" _bytes HEX)
    string(LENGTH "${_bytes}" _len)
    set(_arr "")
    set(_i 0)
    while(_i LESS _len)
        string(SUBSTRING "${_bytes}" ${_i} 2 _byte)
        if(_arr STREQUAL "")
            set(_arr "0x${_byte}")
        else()
            string(APPEND _arr ",0x${_byte}")
        endif()
        math(EXPR _i "${_i} + 2")
    endwhile()
    math(EXPR _size "${_len} / 2")
    set(_header_content
        "/* Generated by GenerateCsoHeader.cmake - do not edit. */\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "unsigned char g_raytracing_cso[] = { ${_arr} };\n"
        "unsigned g_raytracing_cso_size = ${_size};\n")
else()
    set(_header_content
        "/* Generated STUB by GenerateCsoHeader.cmake - do not edit. */\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "unsigned char g_raytracing_cso[] = { 0 };\n"
        "unsigned g_raytracing_cso_size = 0;\n")
endif()

file(WRITE "${OUTPUT}" "${_header_content}")
